import { color, font } from '../theme'

const REPORTS = [
  { name: 'Q3 fleet performance summary', by: 'System', date: '01 Sep 2026' },
  { name: 'Ndola Cold Storage — incident report', by: 'Temba N.', date: '29 Aug 2026' },
  { name: 'Pipeline forecast — August', by: 'Chanda K.', date: '25 Aug 2026' },
  { name: 'Commissioning report — Livingstone Lodge', by: 'Bwalya M.', date: '20 Aug 2026' },
]

export default function Reports() {
  return (
    <div style={{ background: color.white, border: `1px solid ${color.line}`, borderRadius: 12, overflow: 'hidden' }}>
      <div style={{ display: 'grid', gridTemplateColumns: '1.8fr 1fr 1fr', padding: '10px 16px', fontSize: 10.5, fontWeight: 700, letterSpacing: '0.5px', textTransform: 'uppercase', color: color.slateSoft, borderBottom: `1px solid ${color.line}` }}>
        <div>Report</div>
        <div>Generated by</div>
        <div>Date</div>
      </div>
      {REPORTS.map((r, i) => (
        <div key={i} style={{ display: 'grid', gridTemplateColumns: '1.8fr 1fr 1fr', padding: '12px 16px', fontSize: 13, borderBottom: `1px solid ${color.mist2}`, alignItems: 'center' }}>
          <div style={{ fontWeight: 600, color: color.ink, fontFamily: font.display }}>{r.name}</div>
          <div style={{ color: color.slate }}>{r.by}</div>
          <div style={{ color: color.slate }}>{r.date}</div>
        </div>
      ))}
    </div>
  )
}
